#!/usr/bin/env python3
from __future__ import annotations

import argparse
from collections import defaultdict
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SOURCE = ROOT / "source" / "shadowrocket-custom-rules.list"
DEFAULT_OUTPUT_DIR = ROOT / "clash" / "rules"

POLICY_FILES = {
    "US": "shadowrocket-us.yaml",
    "JP": "shadowrocket-jp.yaml",
    "TW": "shadowrocket-tw.yaml",
    "AUTO": "shadowrocket-auto.yaml",
    "DIRECT": "shadowrocket-direct.yaml",
    "REJECT": "shadowrocket-reject.yaml",
}


def parse_rules(source: Path) -> dict[str, list[str]]:
    grouped: dict[str, list[str]] = defaultdict(list)
    for line_number, raw_line in enumerate(
        source.read_text(encoding="utf-8").splitlines(), start=1
    ):
        line = raw_line.split("#", 1)[0].strip()
        if not line:
            continue
        parts = [part.strip() for part in line.split(",")]
        if len(parts) < 3:
            raise ValueError(f"{source}:{line_number}: malformed rule: {raw_line}")
        policy = parts[-1]
        if policy not in POLICY_FILES:
            raise ValueError(
                f"{source}:{line_number}: unsupported Shadowrocket policy {policy!r}"
            )
        grouped[policy].append(",".join(parts[:-1]))
    return grouped


def yaml_quote(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def render_provider(source: Path, policy: str, rules: list[str]) -> str:
    header = (
        "# Generated by scripts/build_clash_rule_providers.py.\n"
        f"# Source: {source.relative_to(ROOT)} ({policy} policy without the policy field).\n"
        "# Do not edit this file directly.\n"
        "payload:\n"
    )
    return header + "".join(f"  - {yaml_quote(rule)}\n" for rule in rules)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", type=Path, default=DEFAULT_SOURCE)
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    args = parser.parse_args()

    grouped = parse_rules(args.source)
    args.output_dir.mkdir(parents=True, exist_ok=True)
    for policy, rules in grouped.items():
        output = args.output_dir / POLICY_FILES[policy]
        output.write_text(render_provider(args.source, policy, rules), encoding="utf-8")
        print(f"wrote {output} ({len(rules)} rules)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
