#!/usr/bin/env python3
from __future__ import annotations

import argparse
from collections import defaultdict
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SOURCES = [
    ROOT / "source" / "shadowrocket-custom-rules.list",
    ROOT / "source" / "clash-extra-rules.list",
]
DEFAULT_OUTPUT_DIR = ROOT / "clash" / "rules"

POLICY_FILES = {
    "US": "shadowrocket-us.yaml",
    "JP": "shadowrocket-jp.yaml",
    "AUTO": "shadowrocket-auto.yaml",
    "DIRECT": "shadowrocket-direct.yaml",
    "REJECT": "shadowrocket-reject.yaml",
}


def parse_rules(
    source: Path, grouped: dict[str, list[str]] | None = None
) -> dict[str, list[str]]:
    if grouped is None:
        grouped = defaultdict(list)
    for line_number, raw_line in enumerate(
        source.read_text(encoding="utf-8").splitlines(), start=1
    ):
        line = raw_line.split("#", 1)[0].strip()
        if not line:
            continue
        parts = [part.strip() for part in line.split(",")]
        if len(parts) < 3:
            raise ValueError(f"{source}:{line_number}: malformed rule: {raw_line}")
        policy = parts[-1]
        if policy not in POLICY_FILES:
            raise ValueError(
                f"{source}:{line_number}: unsupported Shadowrocket policy {policy!r}"
            )
        rule = ",".join(parts[:-1])
        if rule not in grouped[policy]:
            grouped[policy].append(rule)
    return grouped


def yaml_quote(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def render_provider(sources: list[Path], policy: str, rules: list[str]) -> str:
    names = ", ".join(str(source.relative_to(ROOT)) for source in sources)
    header = (
        "# Generated by scripts/build_clash_rule_providers.py.\n"
        f"# Source: {names} ({policy} policy without the policy field).\n"
        "# Do not edit this file directly.\n"
        "payload:\n"
    )
    return header + "".join(f"  - {yaml_quote(rule)}\n" for rule in rules)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--source", type=Path, action="append", dest="sources", default=None
    )
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    args = parser.parse_args()

    sources = args.sources or DEFAULT_SOURCES
    grouped: dict[str, list[str]] = defaultdict(list)
    for source in sources:
        parse_rules(source, grouped)
    args.output_dir.mkdir(parents=True, exist_ok=True)
    for policy, rules in grouped.items():
        output = args.output_dir / POLICY_FILES[policy]
        output.write_text(render_provider(sources, policy, rules), encoding="utf-8")
        print(f"wrote {output} ({len(rules)} rules)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
